trigger:
  - main

variables:
  # Reference the variable group
  - group: 'pipeline-secrets'  # Variable group name containing the PAT

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Setup Python'

- script: |
    python ./scripts/data_script.py > output.txt
  displayName: 'Run Data Script'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'output.txt'
    artifactName: 'ScriptOutput'
  displayName: 'Publish Build Artifact'

- script: |
    # Install Azure DevOps Extension
    az extension add --name azure-devops

    # Authenticate using Personal Access Token from variable group
    echo "Logging in to Azure DevOps"
    echo "##vso[task.setvariable variable=AZURE_DEVOPS_EXT_PAT;issecret=true;]$(AzureDevOpsPAT)"  

    # Login to Azure DevOps
    az devops login \
      --organization "$(System.TeamFoundationCollectionUri)" 

    # Configure default organization
    az devops configure --defaults 
    organization="$(System.TeamFoundationCollectionUri)"

    # Prepare artifact directory
    mkdir -p artifact
    cp output.txt artifact/
    echo "$(Build.BuildId)" > artifact/version.txt
    
    # Create zip artifact
    zip -r artifact.zip artifact
    
    # Publish to Artifacts Feed
    az artifacts universal publish \
      --organization "$(System.TeamFoundationCollectionUri)" \
      --project "$(System.TeamProject)" \
      --scope project \
      --feed "data-pipeline-feed" \
      --name "data-script-output" \
      --version "1.0.$(Build.BuildId)" \
      --description "Data script output artifact" \
      --path artifact.zip
  displayName: 'Publish to Azure Artifacts Feed'
  env:
    AZURE_DEVOPS_PAT: $(AzureDevOpsPAT)  # Pass PAT as environment variable
