trigger:
  - main

variables:
  # Reference the variable group
  - group: 'pipeline-secrets'  # Variable group name containing the PAT

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Authenticate using Personal Access Token from variable group
    az devops login \
      --organization "https://dev.azure.com/Zanabar777" \
      --token "$(AzureDevOpsPAT)"  # Reference PAT from variable group

    # Prepare artifact
    mkdir -p artifact
    python ./scripts/data_script.py > artifact/output.txt
    echo "$(Build.BuildId)" > artifact/version.txt
    
    # Create zip artifact
    zip -r artifact.zip artifact
    
    # Publish to Artifacts Feed
    az artifacts universal publish \
      --organization "https://dev.azure.com/Zanabar777 \
      --project "YOUR_PROJECT_NAME" \
      --scope project \
      --feed "data-pipeline-feed" \
      --name "data-script-output" \
      --version "1.0.$(Build.BuildId)" \
      --description "Data script output artifact" \
      --path artifact.zip
  displayName: 'Publish to Azure Artifacts Feed'
